from __future__ import annotations

from typing import Protocol, runtime_checkable

from alphapulse.pipeline.contracts import CrawlTask
from alphapulse.runtime.config import Settings
from alphapulse.runtime.rqlite_state import RqliteStateStore
from alphapulse.runtime.state import StateStore


@runtime_checkable
class StateStoreProtocol(Protocol):
    def init_db(self) -> None: ...
    def try_claim_url(self, *, url: str, source: str, kind: str, seed_name: str, min_age) -> bool: ...
    def mark_url_fetched(self, url: str, status: int | None) -> None: ...
    def release_url_claim(self, url: str) -> None: ...
    def upsert_pending_tasks(self, tasks: list[CrawlTask]) -> None: ...
    def load_pending_tasks(
        self,
        seed_name: str | None = None,
        source: str | None = None,
    ) -> list[CrawlTask]: ...
    def delete_pending_task(self, dedupe_key: str) -> None: ...
    def prune_pending_tasks_outside_pubdate_range(self, *, source: str, kind: str, start_ts: int, end_ts: int) -> int: ...
    def record_task_failure(self, *, dedupe_key: str, source: str, failure_kind: str) -> int: ...
    def task_failure_count(self, dedupe_key: str, failure_kind: str) -> int: ...
    def clear_task_failures(self, dedupe_key: str) -> None: ...
    def should_refresh_comments(self, source: str, source_entity_id: str, min_age) -> bool: ...
    def upsert_item(self, source: str, source_entity_id: str, canonical_url: str, metadata: dict) -> None: ...
    def mark_comments_refreshed(self, source: str, source_entity_id: str) -> None: ...


def build_state_store(settings: Settings) -> StateStore | RqliteStateStore:
    if settings.crawl.state_backend == "rqlite":
        return RqliteStateStore(settings.rqlite)
    return StateStore(settings.crawl.state_path)
